<h1>模版文件</h1>
<table>
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Sex</th>
    </tr>
    <tr>
        <td>Mike</td>
        <td>19</td>
        <td>B</td>
    </tr>
    <tr>
        <td>Sun</td>
        <td>17</td>
        <td>G</td>
    </tr>
</table>